name: frontend-auto-upload
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.FRONTEND_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRETKEY }}
        AWS_REGION: 'us-east-1'